### ISSUE TITLE
Kisebb hiba draw() használat 

### ISSUE THREAD

**Issue by B4ited** [FabianGabor/Szamitogep-grafika-01#1]
Szia! 
Gabi nagyon jól megcsináltad a házit. Viszont van egy kis gond vele rajzolásokat mindig a draw() függvényben   szabad használni ez Tanár úr döntése. Gondoltam szolok sajnos én tavaly emiatt sokat szívtam.

**Comment by FabianGabor** [comment]
Draw függvénybe rakni azt, hogy kattintásra vár egyenlő lenne az öngyilkossággal, mert az render blokkoló lenne. A [dokumentációt](https://processing.org/reference/mousePressed_.html) vettem alapul, másképp egyelőre nem tudom, hogy hogyan lehet figyelni a kattintás event-et. 

Már mutattam a forráskódot a tanár úrnak, de nem szólt erről semmit. Még egyeztetek vele. Köszönöm, hogy szóltál!

**Comment by FabianGabor** [comment]
Alternatív megoldás draw() függvényen belül: [https://processing.org/reference/mouseButton.html](https://processing.org/reference/mouseButton.html)

**Comment by B4ited** [comment]
Egyáltalán nem bonnyi de szerintem egyszerübb ha  megmuttatom az én megoldásomat példa ként.
``
boolean first = true, done = false;
int x1, y1,x2,y2;

void setup(){
  size(640,480);
};
void draw(){
  if(done){
     vonalak();
  }
}

void mousePressed(){
  if(first){
    x1 = mouseX;
    y1= mouseY;
    first = false;
    done = false;
  }else{
    x2 = mouseX;
    y2 = mouseY;
      first = true;
      done = true;
  }
}

void vonalak(){
    for(int i = 0;i <= 640;i++){
      point(i,y1); 
      point(i,y2);
    }
    for(int i = 0;i <=480;i++){
      point(x1,i);
      point(x2,i);
    }

}
`` 
Ez az első házi második feladata.
Mousepressedbe raktam  egy logikai kapcsolot ugymond.

**Comment by FabianGabor** [comment]
Annyi a különbség az enyémhez képest, hogy a draw függvényből hívod meg a rajzoló függvényed, ha teljesül a feltétel.
Ezzel több gond is van:

- bonyolítja a kódot 
- lassú (a draw figyel egy változót másodpercenként 10x, illetve a mousePressed figyel egy eseményt; az enyémnél csak eseményt figyel)
- ebben az esetben sem a draw() rajzol, hanem meghív egy függvényt, mint az én esetemben a mousePressed()

Szóval lényeges eltérés nincs. A tanár úr hangsúlyozta az optimális, gyors futásra való törekvést, ez teljesen ellentmond annak. Mindenképpen beszélek vele erről.

**Comment by FabianGabor** [comment]
@B4ited igazad volt, a point() mindenképpen a draw()-on belül kell legyen.
Érdekes lesz úgy megírni függvényeket, hogy azok minden lépés után visszaküldik a kirajzolandó pont koordinátáit majd újra meghívódnak a következő koordináta kiszámolásához...

**Comment by FabianGabor** [comment]
Na, szerintem megoldva: https://github.com/FabianGabor/Szamitogep-grafika-01/blob/b2433641c9fa6fbecf9761faace51fc7a92e8b36/szamitogep_grafika_02/szamitogep_grafika_02.pde

**Comment by B4ited** [comment]
Teljes mértékben egyetértek veled ez sokkal lassabb,  viszont így meglesz a tárgyunk remélhetőleg.  :D
Ha elakadtál nyugodtan írj.
További jó munkát!
